### ISSUE TITLE
Process_cesm_data "IndexVariable object has no attribute 'month'" Error with CESM_LME monthly files

### ISSUE THREAD

**Issue by mplauch** [OGGM/oggm#1206]
Hello, 
Sorry if this is a silly error but I am just trying to run a simple model run using the CESM last millenium ensemble, specifically starting from 1000 CE. I downloaded the monthly averaged TREFHT, PRECC, and PRECL from the [CESM Website here](https://www.earthsystemgrid.org/dataset/ucar.cgd.ccsm4.CESM_CAM5_LME.atm.proc.monthly_ave.html). However I get an error 
in process_gcm_data (after process_cesm_data) that states 
```
2021-02-25 10:11:14: oggm.shop.gcm_climate: AttributeError occurred during task process_gcm_data on RGI60-02.05157: 'IndexVariable' object has no attribute 'month'
```
I've attached the code and full error message below. Is there a preprocessing task I should be doing to the netcdf files to make them work in the code? From my understanding the demo CESM files OGGM provides are derived from these LME files so maybe I am missing a step before using them like this.

Any help is appreciated!

**Code**
```
# Python imports
import time
import logging

# Libs
import matplotlib.pyplot as plt

# Locals
import oggm.cfg as cfg
from oggm import tasks, utils, workflow
from oggm.workflow import execute_entity_task
from oggm.utils import get_demo_file
from oggm.core import gcm_climate

# Module logger
log = logging.getLogger(__name__)

# For timing the run
start = time.time()

# Initialize OGGM and set up the default run parameters
cfg.initialize()

# Local working directory (where OGGM will write its output)
WORKING_DIR = utils.gettempdir('OGGM_KlinakliniTest', home=True)
utils.mkdir(WORKING_DIR, reset=True)
cfg.PATHS['working_dir'] = WORKING_DIR

# Use multiprocessing?
cfg.PARAMS['use_multiprocessing'] = True

# How many grid points around the glacier?
# Make it large if you expect your glaciers to grow large
cfg.PARAMS['border'] = 80

# Go - initialize glacier directories
gdirs = workflow.init_glacier_directories(['RGI60-02.05157'],
                                                  from_prepro_level=3)
###################################################################################################################
######################  Climate Data from 850 #####################################################################
###################################################################################################################

# Additional climate file (CESM)
cfg.PATHS['cesm_temp_file'] = '/home/mlauch/CESM_Hist/b.e11.BLMTRC5CN.f19_g16.001.cam.h0.TREFHT.085001-184912.nc'

cfg.PATHS['cesm_precc_file']  = '/home/mlauch/CESM_Hist/b.e11.BLMTRC5CN.f19_g16.001.cam.h0.PRECC.085001-184912.nc'

cfg.PATHS['cesm_precl_file']  = '/home/mlauch/CESM_Hist/b.e11.BLMTRC5CN.f19_g16.001.cam.h0.PRECL.085001-184912.nc'

workflow.execute_entity_task(gcm_climate.process_cesm_data, gdirs)

# Convert the flowlines to a "glacier" for the ice dynamics module
workflow.execute_entity_task(tasks.init_present_time_glacier, gdirs);

# Run the last 200 years with the default starting point (current glacier)
# and CESM data as input
execute_entity_task(tasks.run_from_climate_data, gdirs,
        climate_filename='gcm_data',
        ys=1001, ye=1848,
        output_filesuffix='_Klinaklini_test')

# Compile output
log.info('Compiling output')
utils.compile_glacier_statistics(gdirs)
ds1 = utils.compile_run_output(gdirs, input_filesuffix='_Klinaklini_test')
```

**Code output and Error Message:**
```
2021-02-25 10:11:10: oggm.shop.gcm_climate: (RGI60-02.05157) process_gcm_data
2021-02-25 10:11:14: oggm.shop.gcm_climate: AttributeError occurred during task process_gcm_data on RGI60-02.05157: 'IndexVariable' object has no attribute 'month'
2021-02-25 10:11:14: oggm.shop.gcm_climate: AttributeError occurred during task process_cesm_data on RGI60-02.05157: 'IndexVariable' object has no attribute 'month'
Traceback (most recent call last):
  File "/home/mlauch/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/core/dataarray.py", line 687, in _getitem_coord
    var = self._coords[key]
KeyError: 'time.month'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_againFeb16.py", line 50, in <module>
    workflow.execute_entity_task(gcm_climate.process_cesm_data, gdirs)
  File "/home/mlauch/oggm/oggm/workflow.py", line 161, in execute_entity_task
    out = [pc(gdir) for gdir in gdirs]
  File "/home/mlauch/oggm/oggm/workflow.py", line 161, in <listcomp>
    out = [pc(gdir) for gdir in gdirs]
  File "/home/mlauch/oggm/oggm/workflow.py", line 100, in __call__
    return call_func(gdir, **self.out_kwargs)
  File "/home/mlauch/oggm/oggm/utils/_workflow.py", line 489, in _entity_task
    out = task_func(gdir, **kwargs)
  File "/home/mlauch/oggm/oggm/shop/gcm_climate.py", line 259, in process_cesm_data
    process_gcm_data(gdir, filesuffix=filesuffix, prcp=prcp, temp=temp,
  File "/home/mlauch/oggm/oggm/utils/_workflow.py", line 489, in _entity_task
    out = task_func(gdir, **kwargs)
  File "/home/mlauch/oggm/oggm/shop/gcm_climate.py", line 101, in process_gcm_data
    ts_tmp_std = ts_tmp_sel.groupby('time.month').std(dim='time')
  File "/home/mlauch/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/core/common.py", line 696, in groupby
    return self._groupby_cls(
  File "/home/mlauch/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/core/groupby.py", line 315, in __init__
    group = obj[group]
  File "/home/mlauch/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/core/dataarray.py", line 698, in __getitem__
    return self._getitem_coord(key)
  File "/home/mlauch/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/core/dataarray.py", line 690, in _getitem_coord
    _, key, var = _get_virtual_variable(
  File "/home/mlauch/anaconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/core/dataset.py", line 181, in _get_virtual_variable
    data = getattr(ref_var, var_name).data
AttributeError: 'IndexVariable' object has no attribute 'month'
```

**Comment by anoukvlug** [comment]
@mplauch, it is not a silly question and you're indeed missing a step. By default the climate data that you feed the function should include the period 1961-1990 CE (that is the reference time frame that the delta method uses). You could for instance use NCO tools to merge the 850-1849 CE to the 1850-2005 CE CESM-LME files. That will solve your issue. (Once you're merging the files, it might be worth to remove variables and possibly areas that you won't need. This will speed up your simulations.) Are you familiar with how to do that?

**Comment by mplauch** [comment]
Thank you very much for such a fast reply! Yes that solved my issue perfectly, I just used ncrcat to concatenate the two timesteps available on the CESM website. 

Thanks again for the help!

Max
