### ISSUE TITLE
Getting error while performing MB calibration and catchment width task

### ISSUE THREAD

**Issue by Igsnrr20192019** [OGGM/oggm#1266]
After updating to OGGM 1.5 I cant success fully run catchment width_geom/correction  tasks, secondly when i run the MB calibration OGGM give me error too. Details of code and errors are here: 
Error 1: tasks.catchment_width_geom, tasks.catchment_width_correction.

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/mannan/miniconda3/envs/oggm_stable/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/mannan/miniconda3/envs/oggm_stable/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/mannan/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/workflow.py", line 100, in __call__
    return call_func(gdir, **self.out_kwargs)
  File "/home/mannan/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/utils/_workflow.py", line 490, in _entity_task
    out = task_func(gdir, **kwargs)
  File "/home/mannan/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/core/centerlines.py", line 1793, in catchment_width_geom
    width, wline = _point_width(normal, pcoord, fl, poly, poly_no)
  File "/home/mannan/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/core/centerlines.py", line 1323, in _point_width
    line = shpg.MultiLineString([line])
  File "/home/mannan/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/shapely/geometry/multilinestring.py", line 53, in __init__
    self._geom, self._ndim = geos_multilinestring_from_py(lines)
  File "/home/mannan/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/shapely/geometry/multilinestring.py", line 138, in geos_multilinestring_from_py
    raise EmptyPartError("Can't create MultiLineString with empty component")
shapely.errors.EmptyPartError: Can't create MultiLineString with empty component
"""

The above exception was the direct cause of the following exception:

EmptyPartError                            Traceback (most recent call last)
<ipython-input-55-7837a4fb5425> in <module>
      7 for task in list_talks:
      8     # The order matters!
----> 9     workflow.execute_entity_task(task, gdirs)

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/workflow.py in execute_entity_task(task, gdirs, **kwargs)
    153     if cfg.PARAMS['use_multiprocessing'] and ng > 1:
    154         mppool = init_mp_pool(cfg.CONFIG_MODIFIED)
--> 155         out = mppool.map(pc, gdirs, chunksize=1)
    156     else:
    157         if ng > 3:

~/miniconda3/envs/oggm_stable/lib/python3.9/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365
    366     def starmap(self, func, iterable, chunksize=None):

~/miniconda3/envs/oggm_stable/lib/python3.9/multiprocessing/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772
    773     def _set(self, i, obj):

~/miniconda3/envs/oggm_stable/lib/python3.9/multiprocessing/pool.py in worker()
    123         job, i, func, args, kwds = task
    124         try:
--> 125             result = (True, func(*args, **kwds))
    126         except Exception as e:
    127             if wrap_exception and func is not _helper_reraises_exception:

~/miniconda3/envs/oggm_stable/lib/python3.9/multiprocessing/pool.py in mapstar()
     46
     47 def mapstar(args):
---> 48     return list(map(*args))
     49
     50 def starmapstar(args):

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/workflow.py in __call__()
     98             return call_func(gdir, **gdir_kwargs)
     99         else:
--> 100             return call_func(gdir, **self.out_kwargs)
    101
    102

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/utils/_workflow.py in _entity_task()
    488                     signal.alarm(cfg.PARAMS['task_timeout'])
    489                 ex_t = time.time()
--> 490                 out = task_func(gdir, **kwargs)
    491                 ex_t = time.time() - ex_t
    492                 if cfg.PARAMS['task_timeout'] > 0:

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/core/centerlines.py in catchment_width_geom()
   1791         # First guess widths
   1792         for i, (normal, pcoord) in enumerate(zip(fl.normals, fl.line.coords)):
-> 1793             width, wline = _point_width(normal, pcoord, fl, poly, poly_no)
   1794             widths[i] = width
   1795             wlines.append(wline)

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/core/centerlines.py in _point_width()
   1321     line = line.intersection(poly)
   1322     if line.type == 'LineString':
-> 1323         line = shpg.MultiLineString([line])
   1324     elif line.type == 'MultiLineString':
   1325         pass  # nothing to be done

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/shapely/geometry/multilinestring.py in __init__()
     51             pass
     52         else:
---> 53             self._geom, self._ndim = geos_multilinestring_from_py(lines)
     54
     55     def shape_factory(self, *args):

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/shapely/geometry/multilinestring.py in geos_multilinestring_from_py()
    136
    137         if lgeos.GEOSisEmpty(geom):
--> 138             raise EmptyPartError("Can't create MultiLineString with empty component")
    139
    140         subs[l] = cast(geom, c_void_p)

EmptyPartError: Can't create MultiLineString with empty component

Error 2: Mass balance Calibration:
# Fetch the reference t* list and associated model parameters
params_url = 'https://cluster.klima.uni-bremen.de/~oggm/ref_mb_params/oggm_v1.4/RGIV62/CRU/centerlines/qc3/pcp2.5'
workflow.download_ref_tstars(base_url=params_url)

# Now calibrate
workflow.execute_entity_task(tasks.local_t_star, gdir);
workflow.execute_entity_task(tasks.mu_star_calibration, gdir);

ValueError                                Traceback (most recent call last)
<ipython-input-59-4e6109f8ea1b> in <module>
      4
      5 # Now calibrate
----> 6 workflow.execute_entity_task(tasks.local_t_star, gdir);
      7 workflow.execute_entity_task(tasks.mu_star_calibration, gdir);

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/workflow.py in execute_entity_task(task, gdirs, **kwargs)
    159                          '%d glaciers with multiprocessing turned off. OGGM '
    160                          'will run faster with multiprocessing turned on.', ng)
--> 161         out = [pc(gdir) for gdir in gdirs]
    162
    163     return out

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/workflow.py in <listcomp>(.0)
    159                          '%d glaciers with multiprocessing turned off. OGGM '
    160                          'will run faster with multiprocessing turned on.', ng)
--> 161         out = [pc(gdir) for gdir in gdirs]
    162
    163     return out

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/workflow.py in __call__(self, arg)
     98             return call_func(gdir, **gdir_kwargs)
     99         else:
--> 100             return call_func(gdir, **self.out_kwargs)
    101
    102

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/utils/_workflow.py in _entity_task(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)
    488                     signal.alarm(cfg.PARAMS['task_timeout'])
    489                 ex_t = time.time()
--> 490                 out = task_func(gdir, **kwargs)
    491                 ex_t = time.time() - ex_t
    492                 if cfg.PARAMS['task_timeout'] > 0:

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/core/climate.py in local_t_star(gdir, ref_df, tstar, bias, clip_mu_star, min_mu_star, max_mu_star)
   1001
   1002     # Get the corresponding mu
-> 1003     years, temp_yr, prcp_yr = mb_yearly_climate_on_glacier(gdir, year_range=yr)
   1004     assert len(years) == (2 * mu_hp + 1)
   1005

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/oggm/core/climate.py in mb_yearly_climate_on_glacier(gdir, year_range)
    676                                                     flatten=False)
    677
--> 678     temp = np.average(temp, axis=0, weights=widths)
    679     prcp = np.average(prcp, axis=0, weights=widths)
    680

<__array_function__ internals> in average(*args, **kwargs)

~/miniconda3/envs/oggm_stable/lib/python3.9/site-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
    398                     "1D weights expected when shapes of a and weights differ.")
    399             if wgt.shape[0] != a.shape[axis]:
--> 400                 raise ValueError(
    401                     "Length of weights not compatible with specified axis.")
    402

ValueError: Length of weights not compatible with specified axis.

**Comment by fmaussion** [comment]
Dear @Igsnrr20192019, thanks for the report. On the first sight it does not look related to OGGM, but we don't have enough information to reproduce your problem. Can you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) ? 

For example you could point to the tutorial you are trying to run, or maybe you'll need to share the data that you use...

**Comment by bearecinos** [comment]
Hi, I will like to feedback to this error too cc. @fmaussion 

When updating my code from version v1.3.2 to the latest commit #1275
My main workflow glacier **RGI60-05.00800** (the one I use to explain my workflow in the PG paper) errors in the tasks.catchment_width_geom. With the same error describe above. 

The error actually comes from [centerlines.py._point_width()#L1300](https://github.com/OGGM/oggm/blob/master/oggm/core/centerlines.py#L1300):

And is due to one intersection resulting in an empty LineString. Shapely cant compute a multilinestring due to lines resulting empty after computing `normal.intersection()` or `line.intersection()` (see below)

Error comes from [shapely.multilinestring.py#L143-L144](https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/multilinestring.py#L143-L144)

output:
```
# First use the external boundaries only
    line = normal.intersection(poly_no_nunataks)
    print(line)
```
.....

```
line = line.intersection(poly)
    print(line)
```

`LINESTRING (51.20586544879527 97.5, 50.16826867615821 99.66826867615821)
MULTILINESTRING ((52.00302223224541 92.50302223224541, 50.89762883231749 94.39762883231749), (50.16069989903221 95.66069989903221, 48.68684203246165 98.18684203246164))
LINESTRING (50.16069989903221 95.66069989903221, 48.68684203246165 98.18684203246164)
LINESTRING EMPTY
LINESTRING EMPTY`

Is there a way to just make this intersections nan's or just skip that width? maybe some filtering of empty Linestring will fix this or is this something related to shapely? Looks to me that we just need to filter empty linestrings

I tried this: 
```
  line = normal.intersection(poly_no_nunataks)
  line = line[~(line.is_empty)]
```
 put did not work... 
 got this other error: `TypeError: 'LineString' object is not subscriptable`

**Comment by fmaussion** [comment]
@bearecinos I cannot reproduce the problem locally. Here is the code I used which runs fine:

```python
# Locals
import oggm.cfg as cfg
from oggm import utils, workflow, tasks, graphics

# Initialize OGGM and set up the default run parameters
cfg.initialize()
rgi_version = '62'

cfg.PARAMS['use_multiprocessing'] = False
cfg.PARAMS['continue_on_error'] = False
cfg.PARAMS['dl_verify'] = False

rgi_ids = ['RGI60-05.00800']

# Geometrical centerline
# Where to store the data
cfg.PATHS['working_dir'] = utils.gettempdir(dirname='OGGM-centerlines', reset=True)

# We start from prepro level 3 with all data ready - note the url here
base_url = 'https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.4/L3-L5_files/CRU/centerlines/qc3/pcp2.5/no_match/'
gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3, prepro_border=40, prepro_base_url=base_url)
gdir_cl = gdirs[0]

# Repeat catchment_width_geom to see if happens in prepro dirs
workflow.execute_entity_task(tasks.catchment_width_geom, gdir_cl);
```

**Comment by bearecinos** [comment]
Thanks @fmaussion will give it another go tomorrow and get back to you...

**Comment by bearecinos** [comment]
Hello again (@fmaussion),

I have updated to the latest version [v1.5.2](https://github.com/OGGM/oggm/releases/tag/v1.5.2) and I don't have this issue any more so maybe this is something shapely related.. Recommend to up date everything dependencies and oggm, as by doing that to the latest version fix this for me. I used pyenv instead of conda though.

**Comment by fmaussion** [comment]
Thanks @bearecinos ! Closing this for now.
