### ISSUE TITLE
NotADirectoryError in get_test_dir on MacOS

### ISSUE THREAD

**Issue by oberrauch** [OGGM/oggm#1294]
Deleting all directories inside the OGGM test directory (since #1064) can result in a error when trying to delete the DS_Store file on MacOS. Following the traceback:
```
Traceback (most recent call last):
  File "/Users/oberrauch/miniconda3/envs/oggm_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-528df78320dc>", line 1, in <module>
    get_test_dir()
  File "/Users/oberrauch/oggm-fork/oggm/tests/funcs.py", line 324, in get_test_dir
    shutil.rmtree(os.path.join(cfg.PATHS['test_dir'], d))
  File "/Users/oberrauch/miniconda3/envs/oggm_env/lib/python3.6/shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "/Users/oberrauch/miniconda3/envs/oggm_env/lib/python3.6/shutil.py", line 376, in _rmtree_unsafe
    onerror(os.listdir, path, sys.exc_info())
  File "/Users/oberrauch/miniconda3/envs/oggm_env/lib/python3.6/shutil.py", line 374, in _rmtree_unsafe
    names = os.listdir(path)
NotADirectoryError: [Errno 20] Not a directory: '/Users/oberrauch/OGGM/tests/.DS_Store'
```
Quick and dirty solution would be to set `ignore_errors=True` in `shutil.rmtree`. The more elaborate solution probably to supply a handler via `onerror`, since this could also happen for other files (even though I'm not sure how the should end up in the `tests` directory in the first place).

**Comment by fmaussion** [comment]
Thanks! That's weird. Does it happen often? I any case, any PR is welcome, no need to be too fancy here.
