### ISSUE TITLE
Missing pytables dependence after pip install

### ISSUE THREAD

**Issue by juseg** [OGGM/oggm#1482]
Is pytables a required dependence missing from `setup.cfg`? After install with pip:

```python
$ python -c "import oggm; oggm.cfg.initialize()"
2022-09-20 15:43:49: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2022-09-20 15:43:49: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2022-09-20 15:43:49: oggm.cfg: Multiprocessing: using all available processors (N=4)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/julien/.local/lib/python3.10/site-packages/oggm/cfg.py", line 664, in initialize
    get_dl_verify_data('dummy_section')
  File "/home/julien/.local/lib/python3.10/site-packages/oggm/utils/_downloads.py", line 263, in get_dl_verify_data
    data = pd.read_hdf(verify_file_path, key=section)
  File "/usr/lib/python3.10/site-packages/pandas/io/pytables.py", line 429, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File "/usr/lib/python3.10/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/usr/lib/python3.10/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
```

**Comment by fmaussion** [comment]
Thanks! Yes indeed. Note that setup.cfg does not list all OGGM requirements, only the necessary ones. PyTables should definitely be added though

**Comment by fmaussion** [comment]
The install doc page lists pytables as of master
