### ISSUE TITLE
Glacier_centerlines test code

### ISSUE THREAD

**Issue by franra9** [OGGM/oggm#1558]
Hi @fmaussion @pat-schmitt @lilianschuster ,

As this is part of the RGI work in progress corresponding to Innsbruck (last email from Fabi, lest meeting), I think is better to open an issue to solve possible issues that could appear while testing `glacier_centerlines`'s new entity task.

I tested the code in my pc (so I have already `gdirs` dowloaded) but now doing it into another pc I think the link I use as `base_url` is deprecated/old and I a bit confused about which `bas_url` should I use to test it.

, the steps are
```
pip install glacier-centerlines
```
then in a python terminal, The line which give me problems is this one:

```
# bese url:
base_url = ('https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/centerlines/w5e5/qc0/pcpwin/match_geod_pergla/')

# Initialize glacier directories
gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3, prepro_border=80, prepro_base_url=base_url)
```

ERROR:
```
>>> gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3, prepro_border=80, prepro_base_url=base_url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/froura/miniconda3/lib/python3.8/site-packages/oggm/workflow.py", line 493, in init_glacier_directories
    raise InvalidParamsError("base url seems unreachable with these "
oggm.exceptions.InvalidParamsError: base url seems unreachable with these parameters: https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/centerlines/w5e5/qc0/pcpwin/match_geod_pergla/RGI62/b_080/L3/

```

<details><summary>Complete code snippet</summary>

```
#code snippet to try glaciercenterlines_rgi centerlines, that is now pip installable (pip install glacier_centelrines) git code in https://github.com/GLIMS-RGI/glacier_centerlines/tree/dev-entity_task
# repo code in 

import os
from oggm import cfg, utils
cfg.initialize(logging_level='WARNING')
from oggm import workflow

#set tmpdir
cfg.PATHS['working_dir'] = utils.gettempdir(dirname='OGGM-new-cls', reset=False)

# try hintereisferner
rgi_ids = ['RGI60-11.00897']

# bese url:
base_url = ('https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/centerlines/w5e5/qc0/pcpwin/match_geod_pergla/')

# Initialize glacier directories
gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3, prepro_border=80, prepro_base_url=base_url)

#import general execution for oggm taks
from oggm.workflow import execute_entity_task

#new package where to take the task from:
import glacier_centerlines as gc

# run
execute_entity_task(gc.centerlines_rgi.compute_centerlines_rgi, gdirs)
```

</details>

**Comment by yanglinlin668** [comment]
I think you need to check your installed oggm version. From the base_url variable, the data is used for oggm 1.6 version.

**Comment by pat-schmitt** [comment]
Hi @franra9,

yes, the v1.6 prepro directories have changed recently and the base url you were using is not available anymore.

I think you can use `base_url = 'https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/2023.1/centerlines/W5E5/'` now.
