### ISSUE TITLE
Error initiating glacier directories using own glacier inventory

### ISSUE THREAD

**Issue by sm20ms045** [OGGM/oggm#1591]
Hi! I was trying to use my glacier shapefile to work with in OGGM. I followed the [tutorial](https://oggm.org/tutorials/stable/notebooks/advanced/use_your_own_inventory.html#case-3-start-from-a-completely-independent-inventory), but was getting an error. At first, I thought there was some problem with my shapefile. However, when I tried using the demo file of the tutorial, it was still giving the same error.

Here is my code:
```python
from oggm import cfg, utils, workflow
import geopandas as gpd
cgidf = gpd.read_file(utils.get_demo_file('cgi2.shp'))
rgidf_simple = utils.cook_rgidf(cgidf, o1_region='13')
print(rgidf_simple)
#rgidf_simple.set_geometry("geometry")
cfg.initialize()
cfg.PARAMS['use_multiprocessing'] = True
cfg.PARAMS['use_rgi_area'] = False
cfg.PARAMS['use_intersects'] = False
cfg.PATHS['working_dir'] = utils.gettempdir(dirname='cook_rgidf', reset=True)
gdirs = workflow.init_glacier_directories(rgidf_simple)
```

The output thrown out is:
```
            RGIId     CenLon     CenLat  ... check_geom Name                                           geometry
0  RGI60-13.00001  84.897508  43.504834  ...       None       POLYGON ((84.88765 43.51793, 84.88820 43.51803...
1  RGI60-13.00002  94.301049  35.673427  ...       None       POLYGON ((94.28628 35.67243, 94.28669 35.67247...
2  RGI60-13.00003  96.293274  29.880223  ...       None       POLYGON ((96.28739 29.88241, 96.28744 29.88235...
3  RGI60-13.00004  92.233827  32.781994  ...       None       POLYGON ((92.23549 32.77855, 92.23501 32.77851...
4  RGI60-13.00005  97.340065  29.196493  ...       None       POLYGON ((97.34704 29.18993, 97.34703 29.18993...

[5 rows x 24 columns]
2023-06-09 14:36:44: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2023-06-09 14:36:44: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2023-06-09 14:36:44: oggm.cfg: Multiprocessing: using all available processors (N=8)
2023-06-09 14:36:44: oggm.cfg: Multiprocessing switched ON after user settings.
2023-06-09 14:36:44: oggm.cfg: PARAMS['use_rgi_area'] changed from `True` to `False`.
2023-06-09 14:36:44: oggm.cfg: PARAMS['use_intersects'] changed from `True` to `False`.
2023-06-09 14:36:44: oggm.workflow: Execute entity tasks [GlacierDirectory] on 5 glaciers
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/geopandas/geodataframe.py", line 436, in crs
    return self.geometry.crs
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/geopandas/geodataframe.py", line 235, in _get_geometry
    raise AttributeError(msg)
AttributeError: You are calling a geospatial method on the GeoDataFrame, but the active geometry column to use has not been set.
There are columns with geometry data type (['geometry']), and you can either set one as the active geometry with df.set_geometry("name") or access the column as a GeoSeries (df["name"]) and call the method directly on it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 6014, in __setattr__
    existing = getattr(self, name)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/geopandas/geodataframe.py", line 438, in crs
    raise AttributeError(
AttributeError: The CRS attribute of a GeoDataFrame without an active geometry column is not defined. Use GeoDataFrame.set_geometry to set the active geometry column.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/oggm/workflow.py", line 108, in __call__
    res = self._call_internal(func, arg, kwargs)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/oggm/workflow.py", line 102, in _call_internal
    return call_func(gdir, **kwargs)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/oggm/utils/_workflow.py", line 2695, in __init__
    self._reproject_and_write_shapefile(rgi_entity)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/oggm/utils/_workflow.py", line 2771, in _reproject_and_write_shapefile
    towrite.crs = proj4_str
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/geopandas/geodataframe.py", line 205, in __setattr__
    super().__setattr__(attr, val)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 6030, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/geopandas/geodataframe.py", line 448, in crs
    raise ValueError(
ValueError: Assigning CRS to a GeoDataFrame without a geometry column is not supported. Use GeoDataFrame.set_geometry to set the active geometry column.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sm20ms045/intern23/python/test.py", line 13, in <module>
    gdirs = workflow.init_glacier_directories(rgidf_simple)
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/oggm/workflow.py", line 452, in init_glacier_directories
    gdirs = execute_entity_task(utils.GlacierDirectory, entities,
  File "/home/sm20ms045/.local/lib/python3.10/site-packages/oggm/workflow.py", line 185, in execute_entity_task
    out = mppool.map(pc, gdirs, chunksize=1)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: Assigning CRS to a GeoDataFrame without a geometry column is not supported. Use GeoDataFrame.set_geometry to set the active geometry column.
```

I'm not well acquainted with geopandas, but from what I saw in error, I tried adding the line 'rgidf_simple.set_geometry("geometry")' (commented in the code above), but still getting the same error. In case that matters, I'm running the model on Windows 10 using WSL2. Feel free to let me know if you need any other technical information.

**Comment by pat-schmitt** [comment]
Hi, what are the package versions you are using (oggm and gpd)? This bug was recently fixed (https://github.com/OGGM/oggm/pull/1579) and the code you shared is working for me with the newest oggm version.

**Comment by sm20ms045** [comment]
I'm using oggm v1.6.0 and geopandas v0.13.2
```
sm20ms045@DESKTOP-QVCC002:~$ pip3 show oggm
Name: oggm
Version: 1.6.0
Summary: Open Global Glacier Model
Home-page: https://oggm.org
Author: OGGM Contributors
Author-email: fabien.maussion@uibk.ac.at
License: BSD 3-clause
Location: /home/sm20ms045/.local/lib/python3.10/site-packages
Requires: configobj, matplotlib, netcdf4, numpy, pandas, requests, scipy, shapely, xarray
Required-by:

sm20ms045@DESKTOP-QVCC002:~$ pip3 show geopandas
Name: geopandas
Version: 0.13.2
Summary: Geographic pandas extensions
Home-page:
Author:
Author-email: Kelsey Jordahl <kjordahl@alum.mit.edu>
License: BSD 3-Clause
Location: /home/sm20ms045/.local/lib/python3.10/site-packages
Requires: fiona, packaging, pandas, pyproj, shapely
Required-by:
```

**Comment by pat-schmitt** [comment]
Ok, you have two options, downgrade geopandas to a version before v0.13.0 or update oggm to the latest version from github.

**Comment by sm20ms045** [comment]
Updated oggm to the latest version. It works now for me.
Thank you :)
