### ISSUE TITLE
Installing pip dependencies: failed when I install oggm by the environment.yml file

### ISSUE THREAD

**Issue by chen0954** [OGGM/oggm#1621]
When I use the yml file to configure the environment, the following error occurs, can anyone know how to fix it?

```
(base)` cyq@chen:/home/work$ mamba env create -f environment.yml
conda-forge/noarch                                  13.8MB @   3.1MB/s  4.5s
conda-forge/linux-64                                33.7MB @   4.2MB/s  8.4s


Looking for: ['numpy', 'scipy', 'pandas', 'shapely', 'matplotlib', 'pillow', 'netcdf4', 'scikit-image', 'configobj', 'xarray', 'pytest', 'dask', 'bottleneck', 'pyproj', 'cartopy', 'geopandas', 'rasterio', 'rioxarray', 'seaborn', 'pytables', 'salem', 'motionless', 'pip']


Transaction

  Prefix: /home/cyq/mambaforge/envs/oggm_env

  Updating specs:

   - numpy
   - scipy
   - pandas
   - shapely
   - matplotlib
   - pillow
   - netcdf4
   - scikit-image
   - configobj
   - xarray
   - pytest
   - dask
   - bottleneck
   - pyproj
   - cartopy
   - geopandas
   - rasterio
   - rioxarray
   - seaborn
   - pytables
   - salem
   - motionless
   - pip


  Package                           Version  Build                    Channel                    Size
───────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                       0.1  conda_forge              conda-forge/linux-64     Cached
  + _openmp_mutex                       4.5  2_gnu                    conda-forge/linux-64     Cached
  + affine                            2.4.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + alsa-lib                          1.2.9  hd590300_0               conda-forge/linux-64     Cached
  + aom                               3.5.0  h27087fc_0               conda-forge/linux-64     Cached
  + attr                              2.5.1  h166bdaf_1               conda-forge/linux-64     Cached
  + attrs                            23.1.0  pyh71513ae_1             conda-forge/noarch       Cached
  + aws-c-auth                        0.7.3  h28f7589_1               conda-forge/linux-64     Cached
  + aws-c-cal                         0.6.1  hc309b26_1               conda-forge/linux-64     Cached
  + aws-c-common                      0.9.0  hd590300_0               conda-forge/linux-64     Cached
  + aws-c-compression                0.2.17  h4d4d85c_2               conda-forge/linux-64     Cached
  + aws-c-event-stream                0.3.1  h2e3709c_4               conda-forge/linux-64     Cached
  + aws-c-http                       0.7.11  h00aa349_4               conda-forge/linux-64     Cached
  + aws-c-io                        0.13.32  h4a1a131_0               conda-forge/linux-64     Cached
  + aws-c-mqtt                        0.9.3  hb447be9_1               conda-forge/linux-64     Cached
  + aws-c-s3                         0.3.14  hf3aad02_1               conda-forge/linux-64     Cached
  + aws-c-sdkutils                   0.1.12  h4d4d85c_1               conda-forge/linux-64     Cached
  + aws-checksums                    0.1.17  h4d4d85c_1               conda-forge/linux-64     Cached
  + aws-crt-cpp                      0.21.0  hb942446_5               conda-forge/linux-64     Cached
  + aws-sdk-cpp                     1.10.57  h85b1a90_19              conda-forge/linux-64     Cached
  + blosc                            1.21.4  h0f2a231_0               conda-forge/linux-64     Cached
  + bokeh                             3.2.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + boost-cpp                        1.78.0  h6582d0a_3               conda-forge/linux-64     Cached
  + bottleneck                        1.3.7  py311hcb2cf0a_0          conda-forge/linux-64     Cached
  + branca                            0.6.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + brotli                            1.0.9  h166bdaf_9               conda-forge/linux-64     Cached
  + brotli-bin                        1.0.9  h166bdaf_9               conda-forge/linux-64     Cached
  + brotli-python                     1.0.9  py311ha362b79_9          conda-forge/linux-64     Cached
  + brunsli                             0.1  h9c3ff4c_0               conda-forge/linux-64     Cached
  + bzip2                             1.0.8  h7f98852_4               conda-forge/linux-64     Cached
  + c-ares                           1.19.1  hd590300_0               conda-forge/linux-64     Cached
  + c-blosc2                         2.10.2  hb4ffafa_0               conda-forge/linux-64     Cached
  + ca-certificates               2023.7.22  hbcca054_0               conda-forge/linux-64     Cached
  + cairo                            1.16.0  hbbf8b49_1016            conda-forge/linux-64     Cached
  + cartopy                          0.22.0  py311h320fe9a_0          conda-forge/linux-64     Cached
  + certifi                       2023.7.22  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + cfitsio                           4.3.0  hbdc6101_0               conda-forge/linux-64     Cached
  + cftime                            1.6.2  py311h4c7f6c3_1          conda-forge/linux-64     Cached
  + charls                            2.4.2  h59595ed_0               conda-forge/linux-64     Cached
  + charset-normalizer                3.2.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + click                             8.1.7  unix_pyh707e725_0        conda-forge/noarch       Cached
  + click-plugins                     1.1.1  py_0                     conda-forge/noarch       Cached
  + cligj                             0.7.2  pyhd8ed1ab_1             conda-forge/noarch       Cached
  + cloudpickle                       2.2.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + colorama                          0.4.6  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + configobj                         5.0.8  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + contourpy                         1.1.0  py311h9547e67_0          conda-forge/linux-64     Cached
  + cycler                           0.11.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + cytoolz                          0.12.2  py311h459d7ec_0          conda-forge/linux-64     Cached
  + dask                           2023.8.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + dask-core                      2023.8.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + dav1d                             1.2.1  hd590300_0               conda-forge/linux-64     Cached
  + dbus                             1.13.6  h5008d03_3               conda-forge/linux-64     Cached
  + distributed                    2023.8.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + exceptiongroup                    1.1.3  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + expat                             2.5.0  hcb278e6_1               conda-forge/linux-64     Cached
  + fiona                             1.9.4  py311hbac4ec9_0          conda-forge/linux-64     Cached
  + folium                           0.14.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + font-ttf-dejavu-sans-mono          2.37  hab24e00_0               conda-forge/noarch       Cached
  + font-ttf-inconsolata              3.000  h77eed37_0               conda-forge/noarch       Cached
  + font-ttf-source-code-pro          2.038  h77eed37_0               conda-forge/noarch       Cached
  + font-ttf-ubuntu                    0.83  hab24e00_0               conda-forge/noarch       Cached
  + fontconfig                       2.14.2  h14ed4e7_0               conda-forge/linux-64     Cached
  + fonts-conda-ecosystem                 1  0                        conda-forge/noarch       Cached
  + fonts-conda-forge                     1  0                        conda-forge/noarch       Cached
  + fonttools                        4.42.1  py311h459d7ec_0          conda-forge/linux-64     Cached
  + freetype                         2.12.1  hca18f0e_1               conda-forge/linux-64     Cached
  + freexl                            1.0.6  h166bdaf_1               conda-forge/linux-64     Cached
  + fsspec                         2023.6.0  pyh1a96a4e_0             conda-forge/noarch       Cached
  + gdal                              3.7.1  py311h1caf18b_6          conda-forge/linux-64     Cached
  + geopandas                        0.13.2  pyhd8ed1ab_1             conda-forge/noarch       Cached
  + geopandas-base                   0.13.2  pyha770c72_1             conda-forge/noarch       Cached
  + geos                             3.12.0  h59595ed_0               conda-forge/linux-64     Cached
  + geotiff                           1.7.1  h22adcc9_11              conda-forge/linux-64     Cached
  + gettext                          0.21.1  h27087fc_0               conda-forge/linux-64     Cached
  + gflags                            2.2.2  he1b5a44_1004            conda-forge/linux-64     Cached
  + giflib                            5.2.1  h0b41bf4_3               conda-forge/linux-64     Cached
  + glib                             2.76.4  hfc55251_0               conda-forge/linux-64     Cached
  + glib-tools                       2.76.4  hfc55251_0               conda-forge/linux-64     Cached
  + glog                              0.6.0  h6f12383_0               conda-forge/linux-64     Cached
  + graphite2                        1.3.13  h58526e2_1001            conda-forge/linux-64     Cached
  + gst-plugins-base                 1.22.5  hf7dbed1_0               conda-forge/linux-64     Cached
  + gstreamer                        1.22.5  h98fc4e7_0               conda-forge/linux-64     Cached
  + harfbuzz                          7.3.0  hdb3a94d_0               conda-forge/linux-64     Cached
  + hdf4                             4.2.15  h501b40f_6               conda-forge/linux-64     Cached
  + hdf5                             1.14.1  nompi_h4f84152_100       conda-forge/linux-64     Cached
  + icu                                72.1  hcb278e6_0               conda-forge/linux-64     Cached
  + idna                                3.4  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + imagecodecs                   2023.8.12  py311h67b54e4_0          conda-forge/linux-64     Cached
  + imageio                          2.31.1  pyh24c5eb1_0             conda-forge/noarch       Cached
  + importlib-metadata                6.8.0  pyha770c72_0             conda-forge/noarch       Cached
  + importlib_metadata                6.8.0  hd8ed1ab_0               conda-forge/noarch       Cached
  + iniconfig                         2.0.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + jinja2                            3.1.2  pyhd8ed1ab_1             conda-forge/noarch       Cached
  + joblib                            1.3.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + json-c                             0.17  h7ab15ed_0               conda-forge/linux-64     Cached
  + jxrlib                              1.1  h7f98852_2               conda-forge/linux-64     Cached
  + kealib                            1.5.1  h3e6883b_4               conda-forge/linux-64     Cached
  + keyutils                          1.6.1  h166bdaf_0               conda-forge/linux-64     Cached
  + kiwisolver                        1.4.4  py311h4dd048b_1          conda-forge/linux-64     Cached
  + krb5                             1.21.2  h659d440_0               conda-forge/linux-64     Cached
  + lame                              3.100  h166bdaf_1003            conda-forge/linux-64     Cached
  + lazy_loader                         0.3  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + lcms2                              2.15  haa2dc70_1               conda-forge/linux-64     Cached
  + ld_impl_linux-64                   2.40  h41732ed_0               conda-forge/linux-64     Cached
  + lerc                              4.0.0  h27087fc_0               conda-forge/linux-64     Cached
  + libabseil                    20230125.3  cxx17_h59595ed_0         conda-forge/linux-64     Cached
  + libaec                            1.0.6  hcb278e6_1               conda-forge/linux-64     Cached
  + libarchive                        3.6.2  h039dbb9_1               conda-forge/linux-64     Cached
  + libarrow                         12.0.1  h10ac928_8_cpu           conda-forge/linux-64     Cached
  + libavif                          0.11.1  h8182462_2               conda-forge/linux-64     Cached
  + libblas                           3.9.0  17_linux64_openblas      conda-forge/linux-64     Cached
  + libbrotlicommon                   1.0.9  h166bdaf_9               conda-forge/linux-64     Cached
  + libbrotlidec                      1.0.9  h166bdaf_9               conda-forge/linux-64     Cached
  + libbrotlienc                      1.0.9  h166bdaf_9               conda-forge/linux-64     Cached
  + libcap                             2.69  h0f662aa_0               conda-forge/linux-64     Cached
  + libcblas                          3.9.0  17_linux64_openblas      conda-forge/linux-64     Cached
  + libclang                         15.0.7  default_h7634d5b_3       conda-forge/linux-64     Cached
  + libclang13                       15.0.7  default_h9986a30_3       conda-forge/linux-64     Cached
  + libcrc32c                         1.1.2  h9c3ff4c_0               conda-forge/linux-64     Cached
  + libcups                           2.3.3  h4637d8d_4               conda-forge/linux-64     Cached
  + libcurl                           8.2.1  hca28451_0               conda-forge/linux-64     Cached
  + libdeflate                         1.18  h0b41bf4_0               conda-forge/linux-64     Cached
  + libedit                    3.1.20191231  he28a2e2_2               conda-forge/linux-64     Cached
  + libev                              4.33  h516909a_1               conda-forge/linux-64     Cached
  + libevent                         2.1.12  hf998b51_1               conda-forge/linux-64     Cached
  + libexpat                          2.5.0  hcb278e6_1               conda-forge/linux-64     Cached
  + libffi                            3.4.2  h7f98852_5               conda-forge/linux-64     Cached
  + libflac                           1.4.3  h59595ed_0               conda-forge/linux-64     Cached
  + libgcc-ng                        13.1.0  he5830b7_0               conda-forge/linux-64     Cached
  + libgcrypt                        1.10.1  h166bdaf_0               conda-forge/linux-64     Cached
  + libgdal                           3.7.1  hd2ada2b_6               conda-forge/linux-64     Cached
  + libgfortran-ng                   13.1.0  h69a702a_0               conda-forge/linux-64     Cached
  + libgfortran5                     13.1.0  h15d22d2_0               conda-forge/linux-64     Cached
  + libglib                          2.76.4  hebfc3b9_0               conda-forge/linux-64     Cached
  + libgomp                          13.1.0  he5830b7_0               conda-forge/linux-64     Cached
  + libgoogle-cloud                  2.12.0  h840a212_1               conda-forge/linux-64     Cached
  + libgpg-error                       1.47  h71f35ed_0               conda-forge/linux-64     Cached
  + libgrpc                          1.56.2  h3905398_1               conda-forge/linux-64     Cached
  + libiconv                           1.17  h166bdaf_0               conda-forge/linux-64     Cached
  + libjpeg-turbo                   2.1.5.1  h0b41bf4_0               conda-forge/linux-64     Cached
  + libkml                            1.3.0  h37653c0_1015            conda-forge/linux-64     Cached
  + liblapack                         3.9.0  17_linux64_openblas      conda-forge/linux-64     Cached
  + libllvm15                        15.0.7  h5cf9203_3               conda-forge/linux-64     Cached
  + libnetcdf                         4.9.2  nompi_h7e745eb_109       conda-forge/linux-64     Cached
  + libnghttp2                       1.52.0  h61bc06f_0               conda-forge/linux-64     Cached
  + libnsl                            2.0.0  h7f98852_0               conda-forge/linux-64     Cached
  + libnuma                          2.0.16  h0b41bf4_1               conda-forge/linux-64     Cached
  + libogg                            1.3.4  h7f98852_1               conda-forge/linux-64     Cached
  + libopenblas                      0.3.23  pthreads_h80387f5_0      conda-forge/linux-64     Cached
  + libopus                           1.3.1  h7f98852_1               conda-forge/linux-64     Cached
  + libpng                           1.6.39  h753d276_0               conda-forge/linux-64     Cached
  + libpq                              15.4  hfc447b1_0               conda-forge/linux-64     Cached
  + libprotobuf                      4.23.3  hd1fb520_0               conda-forge/linux-64     Cached
  + librttopo                         1.1.0  hb58d41b_14              conda-forge/linux-64     Cached
  + libsndfile                        1.2.2  hbc2eb40_0               conda-forge/linux-64     Cached
  + libspatialindex                   1.9.3  h9c3ff4c_4               conda-forge/linux-64     Cached
  + libspatialite                     5.0.1  h15f6e67_28              conda-forge/linux-64     Cached
  + libsqlite                        3.42.0  h2797004_0               conda-forge/linux-64     Cached
  + libssh2                          1.11.0  h0841786_0               conda-forge/linux-64     Cached
  + libstdcxx-ng                     13.1.0  hfd8a6a1_0               conda-forge/linux-64     Cached
  + libsystemd0                         254  h3516f8a_0               conda-forge/linux-64     Cached
  + libthrift                        0.18.1  h8fd135c_2               conda-forge/linux-64     Cached
  + libtiff                           4.5.1  h8b53f26_0               conda-forge/linux-64     Cached
  + libutf8proc                       2.8.0  h166bdaf_0               conda-forge/linux-64     Cached
  + libuuid                          2.38.1  h0b41bf4_0               conda-forge/linux-64     Cached
  + libvorbis                         1.3.7  h9c3ff4c_0               conda-forge/linux-64     Cached
  + libwebp-base                      1.3.1  hd590300_0               conda-forge/linux-64     Cached
  + libxcb                             1.15  h0b41bf4_0               conda-forge/linux-64     Cached
  + libxkbcommon                      1.5.0  h5d7e998_3               conda-forge/linux-64     Cached
  + libxml2                          2.11.5  h0d562d8_0               conda-forge/linux-64     Cached
  + libzip                            1.9.2  hc929e4a_1               conda-forge/linux-64     Cached
  + libzlib                          1.2.13  hd590300_5               conda-forge/linux-64     Cached
  + libzopfli                         1.0.3  h9c3ff4c_0               conda-forge/linux-64     Cached
  + locket                            1.0.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + lz4                               4.3.2  py311h9f220a4_0          conda-forge/linux-64     Cached
  + lz4-c                             1.9.4  hcb278e6_0               conda-forge/linux-64     Cached
  + lzo                                2.10  h516909a_1000            conda-forge/linux-64     Cached
  + mapclassify                       2.5.0  pyhd8ed1ab_1             conda-forge/noarch       Cached
  + markupsafe                        2.1.3  py311h459d7ec_0          conda-forge/linux-64     Cached
  + matplotlib                        3.7.2  py311h38be061_0          conda-forge/linux-64     Cached
  + matplotlib-base                   3.7.2  py311h54ef318_0          conda-forge/linux-64     Cached
  + motionless                        1.3.3  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + mpg123                           1.31.3  hcb278e6_0               conda-forge/linux-64     Cached
  + msgpack-python                    1.0.5  py311ha3edf6b_0          conda-forge/linux-64     Cached
  + munch                             4.0.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + munkres                           1.1.4  pyh9f0ad1d_0             conda-forge/noarch       Cached
  + mysql-common                     8.0.33  hf1915f5_2               conda-forge/linux-64     Cached
  + mysql-libs                       8.0.33  hca2cd23_2               conda-forge/linux-64     Cached
  + ncurses                             6.4  hcb278e6_0               conda-forge/linux-64     Cached
  + netcdf4                           1.6.4  nompi_py311h9a7c333_101  conda-forge/linux-64     Cached
  + networkx                            3.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + nomkl                               1.0  h5ca1d4c_0               conda-forge/noarch       Cached
  + nspr                               4.35  h27087fc_0               conda-forge/linux-64     Cached
  + nss                                3.89  he45b914_0               conda-forge/linux-64     Cached
  + numexpr                           2.8.4  py311h039bad6_101        conda-forge/linux-64     Cached
  + numpy                            1.25.2  py311h64a7726_0          conda-forge/linux-64     Cached
  + openjpeg                          2.5.0  hfec8fc6_2               conda-forge/linux-64     Cached
  + openssl                           3.1.2  hd590300_0               conda-forge/linux-64     Cached
  + orc                               1.9.0  h385abfd_1               conda-forge/linux-64     Cached
  + packaging                          23.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pandas                            2.0.3  py311h320fe9a_1          conda-forge/linux-64     Cached
  + partd                             1.4.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + patsy                             0.5.3  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pcre2                             10.40  hc3806b6_0               conda-forge/linux-64     Cached
  + pillow                           10.0.0  py311h0b84326_0          conda-forge/linux-64     Cached
  + pip                              23.2.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pixman                           0.40.0  h36c2ea0_0               conda-forge/linux-64     Cached
  + platformdirs                     3.10.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pluggy                            1.2.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + ply                                3.11  py_1                     conda-forge/noarch       Cached
  + pooch                             1.7.0  pyha770c72_3             conda-forge/noarch       Cached
  + poppler                         23.08.0  hd18248d_0               conda-forge/linux-64     Cached
  + poppler-data                     0.4.12  hd8ed1ab_0               conda-forge/noarch       Cached
  + postgresql                         15.4  h8972f4a_0               conda-forge/linux-64     Cached
  + proj                              9.2.1  ha643af7_0               conda-forge/linux-64     Cached
  + psutil                            5.9.5  py311h2582759_0          conda-forge/linux-64     Cached
  + pthread-stubs                       0.4  h36c2ea0_1001            conda-forge/linux-64     Cached
  + pulseaudio-client                  16.1  hb77b528_4               conda-forge/linux-64     Cached
  + py-cpuinfo                        9.0.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pyarrow                          12.0.1  py311h39c9aba_8_cpu      conda-forge/linux-64     Cached
  + pyparsing                         3.0.9  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pyproj                            3.6.0  py311ha169711_1          conda-forge/linux-64     Cached
  + pyqt                             5.15.9  py311hf0fb5b6_4          conda-forge/linux-64     Cached
  + pyqt5-sip                       12.12.2  py311hb755f60_4          conda-forge/linux-64     Cached
  + pyshp                             2.3.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pysocks                           1.7.1  pyha2e5f31_6             conda-forge/noarch       Cached
  + pytables                          3.8.0  py311h504fbfb_2          conda-forge/linux-64     Cached
  + pytest                            7.4.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + python                           3.11.4  hab00c5b_0_cpython       conda-forge/linux-64     Cached
  + python-dateutil                   2.8.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + python-tzdata                    2023.3  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + python_abi                         3.11  3_cp311                  conda-forge/linux-64     Cached
  + pytz                             2023.3  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + pywavelets                        1.4.1  py311hcb2cf0a_0          conda-forge/linux-64     Cached
  + pyyaml                              6.0  py311hd4cff14_5          conda-forge/linux-64     Cached
  + qt-main                          5.15.8  h7fe3ca9_15              conda-forge/linux-64     Cached
  + rasterio                          1.3.8  py311h41e4db2_0          conda-forge/linux-64     Cached
  + rdma-core                          28.9  h59595ed_1               conda-forge/linux-64     Cached
  + re2                          2023.03.02  h8c504da_0               conda-forge/linux-64     Cached
  + readline                            8.2  h8228510_1               conda-forge/linux-64     Cached
  + requests                         2.31.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + rioxarray                        0.15.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + rtree                             1.0.1  py311h3bb2b0f_2          conda-forge/linux-64     Cached
  + s2n                              1.3.48  h06160fa_0               conda-forge/linux-64     Cached
  + salem                             0.3.9  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + scikit-image                     0.21.0  py311hb755f60_0          conda-forge/linux-64     Cached
  + scikit-learn                      1.3.0  py311hc009520_0          conda-forge/linux-64     Cached
  + scipy                            1.11.2  py311h64a7726_0          conda-forge/linux-64     Cached
  + seaborn                          0.12.2  hd8ed1ab_0               conda-forge/noarch       Cached
  + seaborn-base                     0.12.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + setuptools                       68.1.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + shapely                           2.0.1  py311he06c224_2          conda-forge/linux-64     Cached
  + sip                              6.7.11  py311hb755f60_0          conda-forge/linux-64     Cached
  + six                              1.16.0  pyh6c4a22f_0             conda-forge/noarch       Cached
  + snappy                           1.1.10  h9fff704_0               conda-forge/linux-64     Cached
  + snuggs                            1.4.7  py_0                     conda-forge/noarch       Cached
  + sortedcontainers                  2.4.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + sqlite                           3.42.0  h2c6b66d_0               conda-forge/linux-64     Cached
  + statsmodels                      0.14.0  py311h1f0f07a_1          conda-forge/linux-64     Cached
  + tblib                             1.7.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + threadpoolctl                     3.2.0  pyha21a80b_0             conda-forge/noarch       Cached
  + tifffile                      2023.8.12  pyhd8ed1ab_1             conda-forge/noarch       Cached
  + tiledb                           2.16.3  h84d19f0_1               conda-forge/linux-64     Cached
  + tk                               8.6.12  h27826a3_0               conda-forge/linux-64     Cached
  + toml                             0.10.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + tomli                             2.0.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + toolz                            0.12.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + tornado                           6.3.3  py311h459d7ec_0          conda-forge/linux-64     Cached
  + typing-extensions                 4.7.1  hd8ed1ab_0               conda-forge/noarch       Cached
  + typing_extensions                 4.7.1  pyha770c72_0             conda-forge/noarch       Cached
  + tzcode                            2023c  h0b41bf4_0               conda-forge/linux-64     Cached
  + tzdata                            2023c  h71feb2d_0               conda-forge/noarch       Cached
  + ucx                              1.14.1  h4a2ce2d_3               conda-forge/linux-64     Cached
  + urllib3                           2.0.4  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + wheel                            0.41.1  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + xarray                         2023.8.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + xcb-util                          0.4.0  hd590300_1               conda-forge/linux-64     Cached
  + xcb-util-image                    0.4.0  h8ee46fc_1               conda-forge/linux-64     Cached
  + xcb-util-keysyms                  0.4.0  h8ee46fc_1               conda-forge/linux-64     Cached
  + xcb-util-renderutil               0.3.9  hd590300_1               conda-forge/linux-64     Cached
  + xcb-util-wm                       0.4.1  h8ee46fc_1               conda-forge/linux-64     Cached
  + xerces-c                          3.2.4  h8d71039_2               conda-forge/linux-64     Cached
  + xkeyboard-config                   2.39  hd590300_0               conda-forge/linux-64     Cached
  + xorg-kbproto                      1.0.7  h7f98852_1002            conda-forge/linux-64     Cached
  + xorg-libice                       1.1.1  hd590300_0               conda-forge/linux-64     Cached
  + xorg-libsm                        1.2.4  h7391055_0               conda-forge/linux-64     Cached
  + xorg-libx11                       1.8.6  h8ee46fc_0               conda-forge/linux-64     Cached
  + xorg-libxau                      1.0.11  hd590300_0               conda-forge/linux-64     Cached
  + xorg-libxdmcp                     1.1.3  h7f98852_0               conda-forge/linux-64     Cached
  + xorg-libxext                      1.3.4  h0b41bf4_2               conda-forge/linux-64     Cached
  + xorg-libxrender                  0.9.11  hd590300_0               conda-forge/linux-64     Cached
  + xorg-renderproto                 0.11.1  h7f98852_1002            conda-forge/linux-64     Cached
  + xorg-xextproto                    7.3.0  h0b41bf4_1003            conda-forge/linux-64     Cached
  + xorg-xf86vidmodeproto             2.3.1  h7f98852_1002            conda-forge/linux-64     Cached
  + xorg-xproto                      7.0.31  h7f98852_1007            conda-forge/linux-64     Cached
  + xyzservices                    2023.7.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + xz                                5.2.6  h166bdaf_0               conda-forge/linux-64     Cached
  + yaml                              0.2.5  h7f98852_2               conda-forge/linux-64     Cached
  + zfp                               1.0.0  h27087fc_3               conda-forge/linux-64     Cached
  + zict                              3.0.0  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + zipp                             3.16.2  pyhd8ed1ab_0             conda-forge/noarch       Cached
  + zlib                             1.2.13  hd590300_5               conda-forge/linux-64     Cached
  + zlib-ng                           2.0.7  h0b41bf4_0               conda-forge/linux-64     Cached
  + zstd                              1.5.2  hfc55251_7               conda-forge/linux-64     Cached

  Summary:

  Install: 305 packages

  Total download: 0 B

───────────────────────────────────────────────────────────────────────────────────────────────────────



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/cyq/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/cyq/mambaforge/lib/python3.10/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/cyq/mambaforge/lib/python3.10/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/home/cyq/mambaforge/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 152, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/cyq/mambaforge/lib/python3.10/site-packages/conda_env/installers/pip.py", line 69, in install
        return _pip_install_via_requirements(*args, **kwargs)
      File "/home/cyq/mambaforge/lib/python3.10/site-packages/conda_env/installers/pip.py", line 42, in _pip_install_via_requirements
        requirements = Utf8NamedTemporaryFile(mode='w',
      File "/home/cyq/mambaforge/lib/python3.10/site-packages/conda/auxlib/compat.py", line 38, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(
      File "/home/cyq/mambaforge/lib/python3.10/tempfile.py", line 559, in NamedTemporaryFile
        file = _io.open(dir, mode, buffering=buffering,
      File "/home/cyq/mambaforge/lib/python3.10/tempfile.py", line 556, in opener
        fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/home/cyq/mambaforge/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/home/work/condaenv.9f3in85n.requirements.txt'

`$ /home/cyq/mambaforge/bin/mamba create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/cyq/mambaforge/bin/conda
             CONDA_PREFIX=/home/cyq/mambaforge
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/cyq/mambaforge/bin/python
               CONDA_ROOT=/home/cyq/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/cyq/mambaforge/bin:/home/cyq/mambaforge/condabin:/usr/local/sbin
                          :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/ga
                          mes:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Win
                          dows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt
                          /c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA
                          Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA
                          Corporation/NVIDIA NvDLISR:/mnt/c/Users/chen/AppData/Local/Microsoft/W
                          indowsApps:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/cyq/mambaforge
            shell level : 1
       user config file : /home/cyq/.condarc
 populated config files : /home/cyq/mambaforge/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.31=0
                          __linux=5.15.90.1=0
                          __unix=0=0
       base environment : /home/cyq/mambaforge  (writable)
      conda av data dir : /home/cyq/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/cyq/mambaforge/pkgs
                          /home/cyq/.conda/pkgs
       envs directories : /home/cyq/mambaforge/envs
                          /home/cyq/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/5.15.90.1-microsoft-standard-WSL2 ubuntu/20.04.6 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report. 
```

**Comment by fmaussion** [comment]
The offending line is here:

```
PermissionError: [Errno 13] Permission denied: '/home/work/condaenv.9f3in85n.requirements.txt'
```

It looks like you have not the permission to write here, or not enough space, or similar. In any case it is not related to OGGM, but to your conda installation. Sorry we cannot be of much help here!
