### ISSUE TITLE
'NoneType' object has no attribute 'seek'

### ISSUE THREAD

**Issue by chen0954** [OGGM/oggm#1638]
Dear everyone, after I updated the 1.6.1 version, there is a problem in the step of using OGGM. Can someone help me find out how to solve it?🙏

```
from oggm import cfg, utils
cfg.initialize(logging_level='WARNING')`

`2023-09-02 18:48:41: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2023-09-02 18:48:41: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2023-09-02 18:48:41: oggm.cfg: Multiprocessing: using all available processors (N=16)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 2
      1 from oggm import cfg, utils
----> 2 cfg.initialize(logging_level='WARNING')

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/cfg.py:627, in initialize(file, logging_level, params, future)
    625 # Make sure we have a proper cache dir
    626 from oggm.utils import download_oggm_files, get_demo_file
--> 627 download_oggm_files()
    629 # Read in the demo glaciers
    630 file = os.path.join(os.path.abspath(os.path.dirname(__file__)),
    631                     'data', 'demo_glaciers.csv')

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_downloads.py:830, in download_oggm_files()
    828 def download_oggm_files():
    829     with get_lock():
--> 830         return _download_oggm_files_unlocked()

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_downloads.py:845, in _download_oggm_files_unlocked()
    843 if not os.path.exists(sdir):
    844     ofile = file_downloader(zip_url)
--> 845     with zipfile.ZipFile(ofile) as zf:
    846         zf.extractall(odir)
    847     assert os.path.isdir(sdir)

File ~/mambaforge/envs/oggm_env/lib/python3.10/zipfile.py:1269, in ZipFile.__init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1267 try:
   1268     if mode == 'r':
-> 1269         self._RealGetContents()
   1270     elif mode in ('w', 'x'):
   1271         # set the modified flag so central directory gets written
   1272         # even if no files are added to the archive
   1273         self._didModify = True

File ~/mambaforge/envs/oggm_env/lib/python3.10/zipfile.py:1332, in ZipFile._RealGetContents(self)
   1330 fp = self.fp
   1331 try:
-> 1332     endrec = _EndRecData(fp)
   1333 except OSError:
   1334     raise BadZipFile("File is not a zip file")

File ~/mambaforge/envs/oggm_env/lib/python3.10/zipfile.py:266, in _EndRecData(fpin)
    260 """Return data from the "End of Central Directory" record, or None.
    261 
    262 The data is a list of the nine items in the ZIP "End of central dir"
    263 record followed by a tenth item, the file seek offset of this record."""
    265 # Determine file size
--> 266 fpin.seek(0, 2)
    267 filesize = fpin.tell()
    269 # Check to see if this is ZIP file with no archive comment (the
    270 # "end of central directory" structure should be the last item in the
    271 # file if this is the case).

AttributeError: 'NoneType' object has no attribute 'seek'`
```

**Comment by fmaussion** [comment]
Try deleting the content of `~/.oggm` (hidden `.oggm` folder in your home) and the content of the  `dl_cache_dir` you have indicated in your oggm config. This is the folder printed by:

```python
from oggm import cfg
cfg.PATHS['dl_cache_dir']
```

**Comment by chen0954** [comment]
> 尝试删除（您家中的隐藏文件夹）的内容以及您在 oggm 配置中指示的内容。这是打印的文件夹：`~/.oggm``.oggm``dl_cache_dir`
> 
> ```python
> from oggm import cfg
> cfg.PATHS['dl_cache_dir']
> ```

Thank you for your reply, sorry to bother you again. When I download data, the following error occurs. Do you know how to fix it?

Enter the following data in the Jupyter notebook:
`gdirs = workflow.init_glacier_directories(
    rgi_ids,  # which glaciers?
    prepro_base_url=DEFAULT_BASE_URL,  # where to fetch the data?
    from_prepro_level=4,  # what kind of data? 
    prepro_border=80  # how big of a map?
)`

The error result is as follows:
`---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/workflow.py", line 108, in __call__
    res = self._call_internal(func, arg, kwargs)
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/workflow.py", line 102, in _call_internal
    return call_func(gdir, **kwargs)
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/workflow.py", line 255, in gdir_from_prepro
    return oggm.GlacierDirectory(entity, from_tar=from_tar)
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_workflow.py", line 2640, in __init__
    robust_tar_extract(from_tar, _dir, delete_tar=delete_tar)
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_workflow.py", line 2525, in robust_tar_extract
    _back_up_retry(func, RuntimeError)
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_workflow.py", line 2480, in _back_up_retry
    return func()
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_workflow.py", line 2521, in func
    i_from_tar = tf.getmember(os.path.join(dirbname, bname))
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py", line 1976, in getmember
    tarinfo = self._getmember(name.rstrip('/'))
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py", line 2642, in _getmember
    members = self.getmembers()
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py", line 1987, in getmembers
    self._load()        # all members, we first have to
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py", line 2682, in _load
    tarinfo = self.next()
  File "/home/cyq/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py", line 2589, in next
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data
"""

The above exception was the direct cause of the following exception:

ReadError                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 gdirs = workflow.init_glacier_directories(
      2     rgi_ids,  # which glaciers?
      3     prepro_base_url=DEFAULT_BASE_URL,  # where to fetch the data?
      4     from_prepro_level=4,  # what kind of data? 
      5     prepro_border=80  # how big of a map?
      6 )

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/workflow.py:426, in init_glacier_directories(rgidf, reset, force, from_prepro_level, prepro_border, prepro_rgi_version, prepro_base_url, from_tar, delete_tar)
    424     if cfg.PARAMS['dl_verify']:
    425         utils.get_dl_verify_data('cluster.klima.uni-bremen.de')
--> 426     gdirs = execute_entity_task(gdir_from_prepro, entities,
    427                                 from_prepro_level=from_prepro_level,
    428                                 prepro_border=prepro_border,
    429                                 prepro_rgi_version=prepro_rgi_version,
    430                                 base_url=prepro_base_url)
    431 else:
    432     # We can set the intersects file automatically here
    433     if (cfg.PARAMS['use_intersects'] and
    434             len(cfg.PARAMS['intersects_gdf']) == 0 and
    435             not from_tar):

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/workflow.py:185, in execute_entity_task(task, gdirs, **kwargs)
    183 if cfg.PARAMS['use_multiprocessing'] and ng > 1:
    184     mppool = init_mp_pool(cfg.CONFIG_MODIFIED)
--> 185     out = mppool.map(pc, gdirs, chunksize=1)
    186 else:
    187     if ng > 3:

File ~/mambaforge/envs/oggm_env/lib/python3.10/multiprocessing/pool.py:367, in Pool.map(self, func, iterable, chunksize)
    362 def map(self, func, iterable, chunksize=None):
    363     '''
    364     Apply `func` to each element in `iterable`, collecting the results
    365     in a list that is returned.
    366     '''
--> 367     return self._map_async(func, iterable, mapstar, chunksize).get()

File ~/mambaforge/envs/oggm_env/lib/python3.10/multiprocessing/pool.py:774, in ApplyResult.get(self, timeout)
    772     return self._value
    773 else:
--> 774     raise self._value

File ~/mambaforge/envs/oggm_env/lib/python3.10/multiprocessing/pool.py:125, in worker()
    123 job, i, func, args, kwds = task
    124 try:
--> 125     result = (True, func(*args, **kwds))
    126 except Exception as e:
    127     if wrap_exception and func is not _helper_reraises_exception:

File ~/mambaforge/envs/oggm_env/lib/python3.10/multiprocessing/pool.py:48, in mapstar()
     47 def mapstar(args):
---> 48     return list(map(*args))

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/workflow.py:108, in __call__()
    106 for func in self.call_func:
    107     func, kwargs = func
--> 108     res = self._call_internal(func, arg, kwargs)
    109 return res

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/workflow.py:102, in _call_internal()
     99     gdir, gdir_kwargs = gdir
    100     kwargs.update(gdir_kwargs)
--> 102 return call_func(gdir, **kwargs)

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/workflow.py:255, in gdir_from_prepro()
    252 tar_base = utils.get_prepro_gdir(prepro_rgi_version, rid, prepro_border,
    253                                  from_prepro_level, base_url=base_url)
    254 from_tar = os.path.join(tar_base.replace('.tar', ''), rid + '.tar.gz')
--> 255 return oggm.GlacierDirectory(entity, from_tar=from_tar)

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_workflow.py:2640, in __init__()
   2638 if from_tar is True:
   2639     from_tar = _dir + '.tar.gz'
-> 2640 robust_tar_extract(from_tar, _dir, delete_tar=delete_tar)
   2641 from_tar = False  # to not re-unpack later below
   2642 _shp = os.path.join(_dir, 'outlines.shp')

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_workflow.py:2525, in robust_tar_extract()
   2522             with tf.extractfile(i_from_tar) as fileobj:
   2523                 _robust_extract(to_dir, fileobj=fileobj)
-> 2525     _back_up_retry(func, RuntimeError)
   2527 if delete_tar:
   2528     os.remove(from_tar)

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_workflow.py:2480, in _back_up_retry()
   2478     if count > 0:
   2479         time.sleep(random.uniform(0.05, 0.1))
-> 2480     return func()
   2481 except exceptions:
   2482     count += 1

File ~/mambaforge/envs/oggm_env/lib/python3.10/site-packages/oggm/utils/_workflow.py:2521, in func()
   2519 def func():
   2520     with tarfile.open(base_tar, 'r') as tf:
-> 2521         i_from_tar = tf.getmember(os.path.join(dirbname, bname))
   2522         with tf.extractfile(i_from_tar) as fileobj:
   2523             _robust_extract(to_dir, fileobj=fileobj)

File ~/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py:1976, in getmember()
   1970 def getmember(self, name):
   1971     """Return a TarInfo object for member `name'. If `name' can not be
   1972        found in the archive, KeyError is raised. If a member occurs more
   1973        than once in the archive, its last occurrence is assumed to be the
   1974        most up-to-date version.
   1975     """
-> 1976     tarinfo = self._getmember(name.rstrip('/'))
   1977     if tarinfo is None:
   1978         raise KeyError("filename %r not found" % name)

File ~/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py:2642, in _getmember()
   2638 """Find an archive member by name from bottom to top.
   2639    If tarinfo is given, it is used as the starting point.
   2640 """
   2641 # Ensure that all members have been loaded.
-> 2642 members = self.getmembers()
   2644 # Limit the member search list up to tarinfo.
   2645 skipping = False

File ~/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py:1987, in getmembers()
   1985 self._check()
   1986 if not self._loaded:    # if we want to obtain a list of
-> 1987     self._load()        # all members, we first have to
   1988                         # scan the whole archive.
   1989 return self.members

File ~/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py:2682, in _load()
   2678 """Read through the entire archive file and look for readable
   2679    members.
   2680 """
   2681 while True:
-> 2682     tarinfo = self.next()
   2683     if tarinfo is None:
   2684         break

File ~/mambaforge/envs/oggm_env/lib/python3.10/tarfile.py:2589, in next()
   2587     self.fileobj.seek(self.offset - 1)
   2588     if not self.fileobj.read(1):
-> 2589         raise ReadError("unexpected end of data")
   2591 # Read the next block.
   2592 tarinfo = None

ReadError: unexpected end of data`

**Comment by chen0954** [comment]
> 尝试删除（您家中的隐藏文件夹）的内容以及您在 oggm 配置中指示的内容。这是打印的文件夹：`~/.oggm``.oggm``dl_cache_dir`
> 
> ```python
> from oggm import cfg
> cfg.PATHS['dl_cache_dir']
> ```

Hello, your solution is very good, I solved this problem according to your method a few days ago. But today I got the same error again when using OGGM, and I tried to use the solution you gave to solve the problem again, but without success. Do you know the reason for this problem? Looking forward to your reply, thanks! ! !

**Comment by chen0954** [comment]
> Try deleting the content of `~/.oggm` (hidden `.oggm` folder in your home) and the content of the `dl_cache_dir` you have indicated in your oggm config. This is the folder printed by:
> 
> ```python
> from oggm import cfg
> cfg.PATHS['dl_cache_dir']
> ```

Hello, your solution is very good, I solved this problem according to your method a few days ago. But today I got the same error again when using OGGM, and I tried to use the solution you gave to solve the problem again, but without success. Do you know the reason for this problem? Why does this problem occur? Looking forward to your reply, THANKS! ! !
