### ISSUE TITLE
Error in utils.py / glacier_characteristics(gdirs) task

### ISSUE THREAD

**Issue by bearecinos** [OGGM/oggm#167]
The error appears in this block: 

        # MB and flowline related stuff.......

pacc = np.where(amb >= 0)
            pab = np.where(amb < 0)
            d['aar'] = np.sum(widths[pacc]) / np.sum(widths[pab])
            mb_slope, _, _, _, _ = stats.linregress(h[pab], amb[pab])
            d['mb_grad'] = mb_slope
            d['avg_width'] = np.mean(widths)
            d['avg_slope'] = np.mean(slope)

specifically in 
            d['aar'] = np.sum(widths[pacc]) / np.sum(widths[pab]) 

Traceback (most recent call last):
  File "/home/beatriz/pycharm-community-5.0.4/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/beatriz/pycharm-community-5.0.4/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/home/beatriz/pycharm-community-5.0.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/home/beatriz/oggm-fork/oggm/sandbox/run_alaska.py", line 262, in <module>
    df = utils.glacier_characteristics(gdirs)
  File "/home/beatriz/oggm-fork/oggm/utils.py", line 1277, in glacier_characteristics
    mb_slope, _, _, _, _ = stats.linregress(h[pab], amb[pab])
  File "/home/beatriz/anaconda2/envs/oggm_py3_new/lib/python3.5/site-packages/scipy/stats/_stats_mstats_common.py", line 72, in linregress
    raise ValueError("Inputs must not be empty.")
ValueError: Inputs must not be empty.

**Comment by fmaussion** [comment]
Thanks for the report!

This is now fixed in https://github.com/OGGM/oggm/pull/168
