### ISSUE TITLE
A system setting problem

### ISSUE THREAD

**Issue by maluma013** [OGGM/oggm#1673]
When I try cfg.initialize(), I get the following error:

```
>>> cfg.initialize()
2024-01-13 20:38:14: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.
2024-01-13 20:38:14: oggm.cfg: Multiprocessing switched OFF according to the parameter file.
2024-01-13 20:38:14: oggm.cfg: Multiprocessing: using all available processors (N=8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/oggm/cfg.py", line 653, in initialize
    get_dl_verify_data('dummy_section')
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/oggm/utils/_downloads.py", line 260, in get_dl_verify_data
    data = pd.read_hdf(verify_file_path, key=section)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/pandas/io/pytables.py", line 425, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/pandas/io/pytables.py", line 584, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/pandas/io/pytables.py", line 744, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/tables/file.py", line 294, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/tables/file.py", line 744, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 512, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 836, in H5Fopen
    unable to synchronously open file
  File "H5F.c", line 796, in H5F__open_api_common
    unable to open file
  File "H5VLcallback.c", line 3863, in H5VL_file_open
    open failed
  File "H5VLcallback.c", line 3675, in H5VL__file_open
    open failed
  File "H5VLnative_file.c", line 128, in H5VL__native_file_open
    unable to open file
  File "H5Fint.c", line 2018, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 600, in H5F__super_read
    truncated file: eof = 36044250, sblock->base_addr = 0, stored_eof = 65511439

End of HDF5 error back trace
```
When I first tried utils.get_rgi_dir(version='62'), the data was already downloaded, but this error occurred:
```
>>> utils.get_rgi_dir(version='62')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/oggm/utils/_downloads.py", line 1892, in get_rgi_dir
    return _get_rgi_dir_unlocked(version=version, reset=reset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/site-packages/oggm/utils/_downloads.py", line 1929, in _get_rgi_dir_unlocked
    zf.extractall(rgi_dir)
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/zipfile/__init__.py", line 1721, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/mingzhe/YES/envs/oggm_env/lib/python3.12/zipfile/__init__.py", line 1762, in _extract_member
    raise ValueError("Empty filename.")
ValueError: Empty filename.
```

**Comment by M2tHane** [comment]
Hello, have you solved this problem?

**Comment by M2tHane** [comment]
> Hello, have you solved this problem?

Delete the file “downloads.sha256.hdf”,  and rerun the code to resolve the issue.
