### ISSUE TITLE
RGI50-10.03555 RuntimeError

### ISSUE THREAD

**Issue by sumnonpuella** [OGGM/oggm#263]
I'm attempting to run `init_glacier_region` with an `entity =  gpd.GeoDataFrame.from_file('rgi/10_rgi50_NorthAsia/10_rgi50_NorthAsia.shp')`. 

I have had no troubles running the model with example files, and most of the individual files from the RGI region. RGI50-10.03555 is throwing one specific error, which I seen in other individual files from different regions. The error message changes when I change `cfg.PARAMS['use_multiprocessing]` to False, but the individual files still throws an error.

Is this an error others have encountered, or have advice on working with? 

``` 
Traceback (most recent call last):
  File "/Users/SchmittySmith/oggm/oggm/workflow.py", line 77, in __call__
    return self.call_func(gdir, **gdir_kwargs)
  File "/Users/SchmittySmith/oggm/oggm/utils.py", line 1802, in _entity_task
    out = task_func(gdir, **kwargs)
  File "/Users/SchmittySmith/oggm/oggm/core/preprocessing/gis.py", line 360, in define_glacier_region
    geometry = _check_geometry(geometry)
  File "/Users/SchmittySmith/oggm/oggm/core/preprocessing/gis.py", line 103, in _check_geometry
    assert p.area < 1e-9
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/Users/SchmittySmith/miniconda3/envs/oggm_environment/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/SchmittySmith/miniconda3/envs/oggm_environment/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/SchmittySmith/oggm/oggm/workflow.py", line 84, in __call__
    raise RuntimeError(err_msg) from e
RuntimeError: RGI50-10.03555: exception occured while processing task define_glacier_region
```

**Comment by fmaussion** [comment]
Thanks for the report!

There are quite a few glaciers where OGGM won't work properly, for the reason that it's impossible to catch all possible errors.  The way to go here is to set: ```cfg.PARAMS['continue_on_error'] = True``` after ```cfg.initialize()```

In this case one could also use a debugger and see what exactly is causing this problem...

**Comment by fmaussion** [comment]
@sumnonpuella : I'd be interested in knowing what your plans with OGGM are, would you mind dropping me an email? I'm curious, and since we are still in the process of tuning / setting up the model I'd like to keep you informed when things happen.

**Comment by fmaussion** [comment]
Ah, and you'll need quite a recent version of the model for this to work. I renamed continue_on_error a couple of days ago (https://github.com/OGGM/oggm/pull/258)

**Comment by fmaussion** [comment]
OK, I've seen this too now: will correct in an upcoming PR
