### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by jlandmann** [OGGM/oggm#462]
During my checks for the rgitools hypsometries, I encountered a small error coming from OGGM. Obviously urllib is not happy with the SSL certificate when downloading the GIMP DEM from Klimacluster at Uni Bremen.

I get the following traceback:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\urllib\request.py", line 1254, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\http\client.py", line 1107, in request
        self._send_request(method, url, body, headers)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\http\client.py", line 1152, in _send_request
        self.endheaders(body)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\http\client.py", line 1103, in endheaders
        self._send_output(message_body)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\http\client.py", line 934, in _send_output
        self.send(msg)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\http\client.py", line 877, in send
        self.connect()
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\http\client.py", line 1261, in connect
        server_hostname=server_hostname)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\ssl.py", line 385, in wrap_socket
        _context=self)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\ssl.py", line 760, in __init__
        self.do_handshake()
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\ssl.py", line 996, in do_handshake
        self._sslobj.do_handshake()
    File "C:\Program Files\Anaconda3\envs\oggm_env\lib\ssl.py", line 641, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line     1668, in <module>
        main()
      File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line     1662, in main
        globals = debugger.run(setup['file'], None, None, is_module)
      File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line     1072, in run
        pydev_imports.execfile(file, globals, locals)  # execute the script
      File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_imps        \_pydev_execfile.py", line 18, in execfile
        exec(compile(contents+"\n", file, 'exec'), glob, loc)
      File "C:/Users/Johannes/Documents/rgitools/rgitools/funcs.py", line 487, in <module>
        df = get_hypsometries(rgidf)
      File "C:/Users/Johannes/Documents/rgitools/rgitools/funcs.py", line 77, in wrapper
        out_file = func(*nargs, **kwargs)
      File "C:/Users/Johannes/Documents/rgitools/rgitools/funcs.py", line 425, in get_hypsometries
        rgi_region=rgi_region, rgi_subregion=rgi_subreg)
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 1910, in get_topo_file
        _file = _download_topo_file_from_cluster('gimpdem_90m_v01.1.tif')
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 715, in _download_topo_file_from_cluster
        return _download_topo_file_from_cluster_unlocked(fname)
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 730, in     _download_topo_file_from_cluster_unlocked
        dfile = file_downloader(url)
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 281, in file_downloader
        reset=reset)
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 221, in _progress_urlretrieve
    reporthook=_upd)
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 201, in _urlretrieve
        return _cached_download_helper(cache_obj_name, _dlf, reset)
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 176, in _cached_download_helper
        cache_path = _call_dl_func(dl_func, cache_path)
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 134, in _call_dl_func
        return dl_func(cache_path)
      File "c:\users\johannes\documents\oggm\oggm\utils.py", line 198, in _dlf
        urlretrieve(url, cache_path, *args, **kwargs)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\urllib\request.py", line 188, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\urllib\request.py", line 163, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\urllib\request.py", line 466, in open
        response = self._open(req, data)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\urllib\request.py", line 484, in _open
        '_open', req)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\urllib\request.py", line 444, in _call_chain
        result = func(*args)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\urllib\request.py", line 1297, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "C:\Program Files\Anaconda3\envs\oggm_env\lib\urllib\request.py", line 1256, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed     (_ssl.c:720)>

I wonder if something goes wrong only in my case, as obviously nobody came across this earlier....searching [here](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error) suggests several solutions, I don't know which one (some are bad practice) you would prefer.

**Comment by fmaussion** [comment]
mh that's strange, I'm quite sure I tested this at the time I wrote it. Maybe @TimoRoth as an idea? 

A windows related thing?

**Comment by jlandmann** [comment]
Indeed my `certifi` was a bit older and within the updating process, also `ca-certificates` got updated. Unfortunately though, updating this didn't do the job....is there an easy way to find out if I missed something?
Or any other idea?

**Comment by fmaussion** [comment]
I just tested it and it works fine on my laptop. Can you provide your package versions? What happens if you download the file manually? 

If everything else fails, you can always copy the file manually in your oggm input folder, at the address:
``OGGM_INPUT/download_cache/cluster.klima.uni-bremen.de/~fmaussion/dems/gimpdem_90m_v01.1.tif.zip``

**Comment by jlandmann** [comment]
This is everything I have:

Package | version | latest
-- | -- | --
affine | 2.0.0.post1 | 2.2.0
asn1crypto | 0.24.0 | 0.24.0
bcrypt | 3.1.4 | 3.1.4
bleach | 1.5.0 | 2.1.3
bokeh | 0.12.4 | 0.12.16
boto3 | 1.4.4 | 1.7.23
botocore | 1.5.26 | 1.10.23
bottleneck | 1.2.0 | 1.2.1
ca-certificates | 2018.4.16 |  
cartopy | 0.15.1 | 0.16.0
certifi | 2018.4.16 | 2018.4.16
cffi | 1.11.5 | 1.11.5
chardet | 3.0.4 | 3.0.4
click | 6.7 | 6.7
click-plugins | 1.0.3 | 1.0.3
cligj | 0.4.0 | 0.4.0
cloudpickle | 0.2.2 | 0.5.3
colorama | 0.3.7 | 0.3.9
configobj | 5.0.6 | 5.0.6
cryptography | 2.2.1 | 2.2.2
curl | 7.52.1 |  
cycler | 0.10.0 | 0.10.0
dask | 0.14.0 | 0.17.5
decorator | 4.0.11 | 4.3.0
descartes | 1.0.2 | 1.1.0
distributed | 1.16.0 | 1.21.8
docutils | 0.13.1 | 0.14
ecdsa | 0.13 | 0.13
entrypoints | 0.2.2 | 0.2.3
expat | 2.1.0 |  
fabric3 | 1.14.post1 | 1.14.post1
filelock | 2.0.6 | 3.0.4
fiona | 1.7.4 | 1.8a1
freetype | 2.7 | Milestone1
freexl | 1.0.2 |  
gdal | 2.1.3 | 2.3.0
geopandas | 0.1.1 | 0.3.0
geos | 3.5.1 | 0.2.1
h5netcdf | 0.3.1 | 0.5.1
h5py | 2.6.0 | 2.8.0rc1
hdf4 | 4.2.12 |  
hdf5 | 1.8.17 |  
heapdict | 1.0.0 | 1.0.0
html5lib | 0.999 | 1.0.1
icu | 58.1 |  
idna | 2.6 | 2.6
ipykernel | 4.5.2 | 4.8.2
ipython | 5.3.0 | 6.4.0
ipython_genutils | 0.2.0 | 0.2.0
ipywidgets | 6.0.0 | 7.2.1
jinja2 | 2.9.5 | 2.10
jmespath | 0.9.2 | 0.9.3
joblib | 0.11 | 0.11
jpeg | 9b | 0.1.4
jsonschema | 2.5.1 | 2.6.0
jupyter | 1.0.0 | 1.0.0
jupyter_client | 5.0.0 | 5.2.3
jupyter_console | 5.1.0 | 5.2.0
jupyter_core | 4.3.0 | 4.4.0
kealib | 1.4.6 |  
krb5 | 1.14.2 |  
libiconv | 1.14 |  
libnetcdf | 4.4.1.1 |  
libpng | 1.6.28 |  
libpq | 9.5.4 |  
libspatialite | 4.3.0a |  
libtiff | 4.0.6 | 0.4.2
libxml2 | 2.9.4 |  
libxslt | 1.1.29 |  
locket | 0.2.0 | 0.2.0
lxml | 3.7.3 | 4.2.1
markupsafe | 0.23 | 1.0
matplotlib | 2.0.0 | 2.2.2
mistune | 0.7.3 | 0.8.3
mkl | 2017.0.1 | 2018.0.0
motionless | 1.3.1 | 1.3.2
msgpack-python | 0.4.8 | 0.5.6
munch | 2.1.0 | 2.3.2
nbconvert | 5.1.1 | 5.3.1
nbformat | 4.2.0 | 4.4.0
netcdf4 | 1.2.7 | 1.4.0
networkx | 1.11 | 2.1
notebook | 4.4.1 | 5.5.0
numpy | 1.11.3 | 1.14.3
oggm-deps | 0.1.1.201702171422 |  
olefile | 0.44 | 0.45.1
openjpeg | 2.1.2 |  
openssl | 1.0.2o |  
owslib | 0.14.0 | 0.16.0
pandas | 0.19.2 | 0.23.0
pandoc | 1.19.2 | 1.0.2
pandocfilters | 1.4.1 | 1.4.2
paramiko | 2.3.1 | 2.4.1
partd | 0.3.7 | 0.3.8
pcre | 8.39 |  
pickleshare | 0.7.3 | 0.7.4
pillow | 4.0.0 | 5.1.0
pip | 9.0.1 | 10.0.1
progressbar2 | 3.9.4 | 3.37.1
proj4 | 4.9.3 |  
prompt_toolkit | 1.0.13 | 1.0.15
psutil | 5.2.0 | 5.4.5
py | 1.4.33 | 1.5.3
pyasn1 | 0.4.2 | 0.4.2
pycparser | 2.18 | 2.18
pycrypto | 2.6.1 | 2.6.1
pyepsg | 0.3.1 | 0.3.2
pygments | 2.2.0 | 2.2.0
pynacl | 1.2.1 | 1.2.1
pyopenssl | 18.0.0 | 18.0.0
pyparsing | 2.2.0 | 2.2.0
pyproj | 1.9.5.1 | 1.9.5.1
pyqt | 4.11.4 |  
pyshp | 1.2.10 | 1.2.12
pysocks | 1.6.8 | 1.6.8
pytest | 3.0.7 | 3.5.1
python | 3.5.3 | 2.5
python-dateutil | 2.6.0 | 2.7.3
python-utils | 2.0.0 | 2.3.0
pytz | 2016.10 | 2018.4
pyyaml | 3.12 | 3.12
pyzmq | 16.0.2 | 17.0.0
qt | 4.8.7 | 5.6.2
qtconsole | 4.2.1 | 4.3.1
rasterio | 1.0a8 | 1.0a9
requests | 2.18.4 | 2.18.4
s3fs | 0.0.9 | 0.1.5
s3transfer | 0.1.10 | 0.1.13
salem | 0.0.1.201702161245 | 0.2.1
scikit-image | 0.12.3 | 0.13.1
scipy | 0.19.0 | 1.1.0
setuptools | 33.1.1 | 39.1.0
shapely | 1.5.17 | 1.6.4.post1
simplegeneric | 0.8.1 | 0.8.1
sip | 4.18 | 4.19.8
six | 1.10.0 | 1.11.0
snuggs | 1.4.1 | 1.4.1
sortedcontainers | 1.5.3 | 1.5.10
sqlite | 3.13.0 |  
tblib | 1.3.0 | 1.3.2
testpath | 0.3 | 0.3.1
toolz | 0.8.2 | 0.9.0
tornado | 4.4.2 | 5.0.2
traitlets | 4.3.2 | 4.3.2
urllib3 | 1.22 | 1.22
vc | 14 |  
vs2015_runtime | 14.0.25420 |  
wcwidth | 0.1.7 | 0.1.7
webencodings | 0.5 | 0.5.1
wheel | 0.29.0 | 0.31.1
widgetsnbextension | 2.0.0 | 3.2.1
win_inet_pton | 1.0.1 | 1.0.1
win_unicode_console | 0.5 | 0.5
wincertstore | 0.2 | 0.2

Manual download via the browser of course works, via a small script in Python unfortunately no. But you are right, probably the problem is somewhere on my machine, so nothing to spend too much time on...

**Comment by fmaussion** [comment]
The workaround in the SO post will probably work with having to change anything in OGGM btw, because it makes a monkeypatch of python internals. However, it would be better to find the reason for this on your laptop...

**Comment by TimoRoth** [comment]
This looks similar to this: https://github.com/ContinuumIO/anaconda-issues/issues/494#issuecomment-155097614

Someone also found out today that the Windows-Firewall can interfere somehow, which still seems weird to me how it would cause a certificate error, but try allowing your python binary full access, or try temporarily disabling the Windows Firewall.

**Comment by jlandmann** [comment]
Thanks for your investigation!!!
Superweird. The update trick didn't work for me...I gave the python.exe of my environment an incoming and outgoing rule in my Firewall and then the SSL error is gone, however replaced with a TimeoutError....I guess this could be my fault, ok.
However, it should then definitely work when I switch off the Firewall completely, right? But exactly then the SSL Error occurs again...

I now made a fresh oggm environment and followed again the instructions from the issue you found, but still exactly the same happens.
I'm unfortunately a bit under pressure now...if you want to leave this open I can look in approx. five weeks for a better solution or we can just close it and as soon I find the time I would reopen.

**Comment by fmaussion** [comment]
I know a very easy fix to that problem ;-)

**Comment by jlandmann** [comment]
Switch to Linux? ;-P

**Comment by fmaussion** [comment]
You said it!

**Comment by fmaussion** [comment]
Closing this, let us know if this happens again.

**Comment by TimoRoth** [comment]
I just realized we do not use requests, but plain python urllib. urllib does not use certifi at all, but instead tries to use the system cert store, which has varying rates of success depending on the system.

I will soon make some changes to either use requests instead, or just make urllib use the certifi certstore.

**Comment by jlandmann** [comment]
Sorry for the late reply, I'm finally back...
I pulled your changes and everything seems to work fine on Windows, too, now! Thanks a lot for your great work!
