### ISSUE TITLE
Error: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte.

### ISSUE THREAD

**Issue by rylanlee** [OGGM/oggm#917]
When I run the example of [Run the mass-balance calibration](https://oggm.readthedocs.io/en/latest/run_examples/run_mb_calibration.html/), the script ends with an error said  **'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte.** 
 Has anyone met with the same problem? How to fix it? Thank you.

**Comment by TimoRoth** [comment]
Which line is throwing that error and what's the complete backtrace?

**Comment by rylanlee** [comment]
Thanks for your attention  @TimoRoth 
The version of OGGM model in my computer is 1.12. It says in my IDE (spyder3) as below:

Traceback (most recent call last):

  File "<ipython-input-1-ea6a7a05715e>", line 1, in <module>
    runfile('/home/liyaojun/mass-balance calibration.py', wdir='/home/liyaojun')

  File "/home/liyaojun/anaconda3/envs/oggm_env112/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/liyaojun/anaconda3/envs/oggm_env112/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/liyaojun/mass-balance calibration.py", line 131, in <module>
    mb_calib = gdirs[0].read_json('climate_info')['mb_calib_params']

  File "/home/liyaojun/anaconda3/envs/oggm_env112/lib/python3.6/site-packages/oggm/utils/_workflow.py", line 1850, in read_json
    out = json.load(f)

  File "/home/liyaojun/anaconda3/envs/oggm_env112/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

  File "/home/liyaojun/anaconda3/envs/oggm_env112/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by TimoRoth** [comment]
That would seem like the climate_info json file in the glacier directory got corrupted in some way.
Can you delete it, so it gets extracted again?

**Comment by rylanlee** [comment]
Hi @TimoRoth , thanks for your kindly help.

I deleted all climate_info.pkl files (259) in the glacier directory but the script still failed with the same error.

However,  as I googled the error info,  maybe there is something wrong in encoding......
