### ISSUE TITLE
Odd error in crossval script

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#935]
https://cluster.klima.uni-bremen.de/~github/crossval_logs/90821.txt

@TimoRoth I don't know if this is related but it happened after your spawn commit: https://github.com/OGGM/oggm/commits/master

(possibly unrelated)

cc @matthiasdusch

**Comment by fmaussion** [comment]
```
Traceback (most recent call last):
  File "/work/github/oggm_mb_crossval/oggm_env/bin/mb_crossval", line 8, in <module>
    sys.exit(main())
  File "/work/github/oggm_mb_crossval/oggm_env/lib/python3.7/site-packages/mbcrossval/__main__.py", line 80, in main
    run_main()
  File "/work/github/oggm_mb_crossval/oggm_env/lib/python3.7/site-packages/mbcrossval/run.py", line 45, in run_main
    website_main()
  File "/work/github/oggm_mb_crossval/oggm_env/lib/python3.7/site-packages/mbcrossval/website.py", line 66, in website_main
    create_minor_website(env, vdf['cru_short'], 'cru_short.html', nbpaths)
  File "/work/github/oggm_mb_crossval/oggm_env/lib/python3.7/site-packages/mbcrossval/website.py", line 322, in create_minor_website
    xvaldict = pickle.load(open(vers['file'], 'rb'))
AttributeError: Can't get attribute 'FrozenNDArray' on <module 'pandas.core.indexes.frozen' from '/usr/local/pyenv/versions/3.7.6/lib/python3.7/site-packages/pandas/core/indexes/frozen.py'>
```

OK, I think it might be due to an update in pandas. The error happens when creating the website and reading pickles.

**Comment by matthiasdusch** [comment]
thanks, I'll have a look

**Comment by fmaussion** [comment]
The easiest might be to pin pandas <1 for now, and avoid pickles in the future.

OGGM should also remove all use of pickles in the next generation of glacier directories - this will be a lot of fun...

**Comment by matthiasdusch** [comment]
pandas<1 works for now. I hope I find the time to update the whole thing soon.
